version: "3.7"

services:
  service-backend:
    build:
      target: prod-stage
    image: image-journal-keeper-backend:prod-stage-2021-09-21-07-56
    container_name: container-journal-keeper-backend-prod-stage
    depends_on:
      - service-mysql
    environment:
      - TYPEORM_CONNECTION=mysql
      - TYPEORM_HOST=journal-keeper-database-server
      - TYPEORM_USERNAME=j-k-u
      - TYPEORM_PASSWORD=j-k-p
      - TYPEORM_DATABASE=j-k-d
      - TYPEORM_PORT=3306
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=true
      - TYPEORM_ENTITIES=dist/entities.js
      - NODE_ENV=prod
    command:
      [
        "./wait-for",
          "journal-keeper-database-server:3306",
          "--timeout=30",  # Value found by manually trying out different ones.
          "--",
            "node", "dist/server.js"
      ]
    expose:
      - "5000"
    ports:
      - "5000:5000"
  
  service-frontend:
    build:
      target: prod-stage
    image: image-journal-keeper-frontend:prod-stage-2021-09-21-07-56
    container_name: container-journal-keeper-frontend-prod-stage
    # depends_on:
    #   - service-backend
    ports:
      - "3000:80"
