version: "3.7"

services:
  service-mysql:
    image: mysql:8.0.26
    container_name: ${DB_ENGINE_HOSTNAME:?env var cannot be unset or empty}
    volumes:
      - volume-journal-keeper-mysql:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DB_ENGINE_DATABASE:?env var cannot be unset or empty}
      - MYSQL_USER=${DB_ENGINE_USERNAME:?env var cannot be unset or empty}
      - MYSQL_PASSWORD=${DB_ENGINE_PASSWORD:?env var cannot be unset or empty}
  
  service-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: build-stage
    image: image-journal-keeper-backend:build-stage-2021-09-23-08-54
    container_name: container-journal-keeper-backend-build-stage
    depends_on:
      - service-mysql
    environment:
      - SECRET_KEY=${SECRET_KEY:?env var cannot be unset or empty}
      - DATABASE_TYPE=${DB_ENGINE_TYPE:?env var cannot be unset or empty}
      - DATABASE_HOSTNAME=${DB_ENGINE_HOSTNAME:?env var cannot be unset or empty}
      - DATABASE_PORT=${DB_ENGINE_PORT:?env var cannot be unset or empty}
      - DATABASE_NAME=${DB_ENGINE_DATABASE:?env var cannot be unset or empty}
      - DATABASE_USERNAME=${DB_ENGINE_USERNAME:?env var cannot be unset or empty}
      - DATABASE_PASSWORD=${DB_ENGINE_PASSWORD:?env var cannot be unset or empty}
    command: 
      [
        "./wait-for",
          "${DB_ENGINE_HOSTNAME:?env var cannot be unset or empty}:${DB_ENGINE_PORT:?env var cannot be unset or empty}",
          "--timeout=30",  # Value found by manually trying out different ones.
          "--",
            "ts-node",
              "./node_modules/typeorm/cli",
              "-f", "./ormconfig.ts",
              "migration:run",
              "-c", "connection-to-db-for-dev"
      ]
  
  service-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: build-stage
    image: image-journal-keeper-frontend:build-stage-2021-09-23-08-54
    container_name: container-journal-keeper-frontend-build-stage

volumes:
  volume-journal-keeper-mysql:
