version: "3.7"

services:
  service-backend:
    build:
      target: prod-stage
    image: image-journal-keeper-backend:prod-stage-2021-09-23-08-54
    container_name: container-journal-keeper-backend-prod-stage
    depends_on:
      - service-mysql
    environment:
      - TYPEORM_CONNECTION=${DB_ENGINE_TYPE:?env var cannot be unset or empty}
      - TYPEORM_HOST=${DB_ENGINE_HOSTNAME:?env var cannot be unset or empty}
      - TYPEORM_PORT=${DB_ENGINE_PORT:?env var cannot be unset or empty}
      - TYPEORM_DATABASE=${DB_ENGINE_DATABASE:?env var cannot be unset or empty}
      - TYPEORM_USERNAME=${DB_ENGINE_USERNAME:?env var cannot be unset or empty}
      - TYPEORM_PASSWORD=${DB_ENGINE_PASSWORD:?env var cannot be unset or empty}
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=true
      - TYPEORM_ENTITIES=dist/entities.js
      - NODE_ENV=prod
    command:
      [
        "./wait-for",
          "${DB_ENGINE_HOSTNAME:?env var cannot be unset or empty}:${DB_ENGINE_PORT:?env var cannot be unset or empty}",
          "--timeout=30",  # Value found by manually trying out different ones.
          "--",
            "node", "dist/server.js"
      ]
    # expose:
    #   - "5000"
    # ports:
    #   - "5000:5000"
  
  service-frontend:
    build:
      target: prod-stage
    image: image-journal-keeper-frontend:prod-stage-2021-09-23-08-54
    container_name: container-journal-keeper-frontend-prod-stage
    # depends_on:
    #   - service-backend
    ports:
      - "3000:80"
